---
title: "Retain Correlation"
output: 
  html_notebook:
    toc: yes
author: Lin Ma
date: 2019-12-20
---

### Package Loading
```{r}
library(caret)
library(e1071)
library(ROCR)
library(ggplot2)
library(corrplot)
library(mice)
library(randomForest)
library(dplyr)
```

### Data Import and Cleaning


```{r}
retain_correlation <- read.csv("Retention Correlation v3.csv", header = TRUE) 
rc <- retain_correlation[,-1]
summary(rc)
rc[is.na(rc)] <- 0
md.pattern(rc)
```


```{r}
#Remove redundant features
set.seed(1224)
correlationMatrix <- cor(rc[,8:19])
print(correlationMatrix)
highlycorrelated<-findCorrelation(correlationMatrix,cutoff = 0.75)
print(highlycorrelated)

#Correlation
corrplot(correlationMatrix,method = "number",type="upper",tl.col = "black",tl.srt = 45,order = "hclust",addCoefasPercent = TRUE, number.cex = .7)
```




```{r}
rc <- rc[,-c(16,18)]
corrplot(cor(rc[,8:17]),method = "number",type="upper",tl.col = "black",tl.srt = 45,order = "hclust", addCoefasPercent = TRUE, number.cex = .7)

set.seed(1015)
findCorrelation(cor(rc[,8:17]),cutoff = 0.75)
```


### Split Dataset

```{r}
set.seed(1)
trainIndex1 <- createDataPartition(rc$if_retain, p=0.7, list = FALSE)
train1 <- rc[trainIndex1,]
test1 <- rc[-trainIndex1,]
```


### Logistic Regression

```{r}
set.seed(2)
control<-trainControl(method = "repeatedcv",number=10,repeats = 3)
model_glm1<-train(if_retain~.,data = train1 ,method='glm',preProcess=c('scale','center'),family="binomial",trControl=control)
summary(model_glm1)
predictions1<-predict(model_glm1,newdata = test1,type="raw")
confusionMatrix(predictions1,test1$if_retain)
```


### Export the Result

```{r}
test1$if_retain_predict <- predictions1
test1$userID <- retain_correlation[-trainIndex1,]$userID
write.csv(test1,file = "player retention prediction v3.csv",row.names = FALSE)
```


### Random Forest

```{r}
set.seed(1223)
# ctrl <- trainControl(method = "repeatedcv", 
#                      number = 10, 
#                      repeats = 3,
#                      verboseIter = FALSE,
#                      allowParallel = TRUE)
model_rf <- caret::train(if_retain ~ .,
                                data = train1,
                                method = "rf",
                                preProcess = c("scale", "center"))
final <- data.frame(actual = test1$if_retain,
                          predict(model_rf, newdata = test1, type = "prob"))
summary(model_rf)
final$predict <- as.factor(ifelse(final$retained > 0.5, "retained", "churned"))
confusionMatrix(final$predict, test1$if_retain)
varImp(model_rf,scale = FALSE)
varImp(model_glm1,scale = FALSE)
```



